export const ru = {
  brand: "Вжик",
  nav: {
    catalog: "Каталог",
    orders: "Мои заказы",
    profile: "Профиль",
  },
  home: {
    deliveryBanner: "Доставка за 15 мин",
    address: "ул. Роз, 12",
    chooseHome: "Выберите свой дом",
    fixedPrice: "Цена товара — фиксированная. Оптовая.",
    deliveryGetsCheaper: "Доставка — дешевеет при коллективном заказе.",
    categories: "Категории",
    sectionCount: "18 разделов",
    freshnessTitle: "Свежесть гарантирована",
    freshnessText: "Проверяем срок годности каждой позиции",
    searchPlaceholder: "Поиск продуктов и товаров",
    benefit: "Выгода дома",
  },
  categories: {
    meat: "Мясо и птица",
    sausage: "Колбасные изделия и деликатесы",
    fish: "Рыба и морепродукты",
    dairy: "Молочные продукты",
    produce: "Овощи, фрукты, зелень",
    eggs: "Яйца",
    grocery: "Бакалея",
    spice: "Специи, соусы, приправы",
    preserves: "Консервы и соленья",
    bread: "Хлеб и выпечка",
    sweets: "Кондитерские изделия",
    frozen: "Полуфабрикаты и заморозка",
    nuts: "Орехи и сухофрукты",
    tea: "Чай, кофе, какао",
    drinks: "Напитки и соки",
    baby: "Детское питание",
    pet: "Корма для животных",
    household: "Бытовая химия и дом",
    milk: "Молоко",
    cheese: "Сыры",
    curd: "Творог",
    yogurt: "Йогурты",
    butter: "Масло",
    cream: "Сливки",
    sour: "Сметана",
  },
  group: {
    back: "Назад в каталог",
    dairyNote: "Прямые поставки с ферм",
    jointTitle: "Совместный закуп",
    jointText: "Цены склада при наборе партии",
    jointDiscount: "До -35%",
  },
  product: {
    weight: "400 г",
    name: "Сыр Гауда 45%",
    fullName: "Сыр Гауда 45%, 400 г",
    producer: "Производитель: Сыроварня Север",
    storePriceLabel: "В магазине",
    storePrice: "349 ₽",
    ourPriceLabel: "Наша цена",
    ourPrice: "289 ₽",
    deliveryLabel: "Доставка",
    deliveryFrom: "Доставка от 50 ₽",
    deliveryAmount: "от 50 ₽",
    wholesaleNote: "Оптовая цена производителя. Не зависит от числа соседей",
    neighborsLeft: "До дешёвой доставки не хватает 6 соседей",
    progressCount: "4/10",
    joinWave: "Присоединиться к волне",
  },
  addressSheet: {
    title: "Выберите свой дом",
    subtitle: "Доставка бесплатна, когда соседи объединяются",
    searchPlaceholder: "Адрес или номер дома",
    youAreHere: "Вы здесь",
    courierLead: "Следующий совместный курьер прибудет через",
    courierTime: "28 минут",
    choose: "Выбрать адрес",
    houses: [
      {
        id: "roz-12",
        line: "ул. Роз, 12",
        neighbors: "В этом доме уже 18 соседей",
        here: true,
      },
      {
        id: "roz-14",
        line: "ул. Роз, 14, корп. 1",
        neighbors: "В этом доме 11 соседей",
        here: false,
      },
      {
        id: "konyushennaya",
        line: "ул. Малая Конюшенная, 8",
        neighbors: "В этом доме 24 соседа",
        here: false,
      },
      {
        id: "nevsky",
        line: "Невский пр-т, 45",
        neighbors: "В этом доме 6 соседей",
        here: false,
      },
    ],
  },
  wave: {
    pay: "Оплатить 351 ₽",
    leave: "Выйти из волны",
    delivered: "Доставлен",
    section: "Мои Заказы",
    number: "Волна #4928",
    productName: "Сыр Гауда 45%, 400 г",
    quantity: "Количество: 1 шт. • Скидка волны 35%",
    price: "289 ₽",
    homeLabel: "Дом",
    home: "ул. Роз, 12",
    statusLabel: "Статус",
    status: "Идёт набор",
    collectUntilLabel: "Срок набора",
    collectUntil: "до 12 октября, 18:00",
    deliveryDateLabel: "Срок поставки",
    deliveryDate: "15 октября",
    progressLabel: "Прогресс",
    progressValue: "28 из 30 соседей (91%)",
    remaining: "Осталось 2 участника для оптовой цены",
    goodsLabel: "Цена товара",
    deliveryCostLabel: "Стоимость доставки",
    deliveryCost: "62 ₽ с человека",
    totalLabel: "Итого",
    total: "351 ₽",
    totalNote: "Включая доставку в подъезд",
    hold: "Деньги резервируются на карте. Списание произойдёт только после успешного закрытия волны 12 октября.",
  },
  waveJoined: {
    title: "Вы в волне.",
    priceLine: "Цена товара — 289 ₽.",
    deliveryLine: "Доставка — когда волна закроется.",
    product: "Сыр Гауда 45%",
    piece: "Фермерский кусок, 350 г",
    retail: "Обычная розничная цена 440 ₽",
    collected: "Собрано 28 из 30 соседей",
    left: "Осталось 2 соседа",
    notice: "Осталось 2 человека для отправки партии курьером по вашему адресу.",
    orders: "Мои заказы",
    catalog: "Вернуться в каталог",
  },
  waveClosed: {
    back: "Назад к заказам",
    placed: "Заказ оформлен",
    finished: "Волна завершена",
    title: "Волна закрыта",
    subtitle: "Волна #4928 • Сыр Гауда 45%",
    summary: "Итоги совместной закупки",
    success: "Успешно",
    name: "Сыр Гауда 45%",
    amount: "400 г • 1 шт.",
    participantsLabel: "Участники",
    participants: "34 соседа",
    courierLabel: "Доставка курьером",
    courierPrice: "62 ₽",
    courierWas: "210 ₽",
    totalLabel: "Итого к оплате",
    note: "Цена товара не изменилась — 289 ₽. Доставка подешевела, потому что вас стало больше.",
    today: "Доставка сегодня",
    courier: "Курьер прибудет сегодня к 19:30 в дом №12",
    details: "Подробности заказа",
  },
  close: "Закрыть",
  orders: {
    title: "История заказов",
    countLabel: "Всего заказов",
    filterAll: "Все заказы",
    filterActive: "Активные",
    filterDelivered: "Доставленные",
    filterArchive: "Архив",
    emptyTitle: "Пока нет заказов",
    emptyText: "Выберите товар и присоединитесь к волне",
    openCatalog: "Открыть каталог",
    totalLabel: "Итого",
    helpTitle: "Нужна помощь с заказом?",
    helpText: "Поддержка на связи 24/7",
    helpAction: "Чат",
    perkTimeTitle: "15–30 мин",
    perkTimeText: "Среднее время доставки по вашему району",
    perkFreeTitle: "От 0 ₽",
    perkFreeText: "Бесплатно при покупке от 800 ₽",
    activeAndArchive: "Активные и архив",
  },
  order: {
    number: "Заказ №1042",
    waveNumber: "Волна #4928 • 12 октября",
    inTransit: "В пути",
    share: "Поделиться",
    statusTitle: "Статус заказа",
    updatedAgo: "Обновлено 2 мин назад",
    stepPaid: "Оплачен",
    stepPaidDesc: "Банковская карта **** 4291",
    stepAssembled: "В сборке",
    stepAssembledDesc: "Укомплектован на складе Север",
    stepInTransit: "В пути",
    stepInTransitToday: "Сегодня",
    stepInTransitDesc: "Курьер прибудет сегодня к 19:30",
    stepInTransitCourier: "Курьер: Алексей В. (+7 ••• ••-40)",
    stepDelivered: "Доставлен",
    stepDeliveredDesc: "Ориентировочно 15 октября",
    qrLabel: "QR-код получения",
    qrReady: "Готов к выдаче",
    qrCodeLabel: "Код: 841-29",
    qrHint: "Покажите курьеру при получении",
    itemsTitle: "Состав заказа",
    itemsCount: "1 позиция",
    goodsLabel: "Товары",
    deliveryLabel: "Доставка курьером",
    totalLabel: "Итого",
    addressTitle: "Адрес доставки",
    addressLine: "ул. Малая Конюшенная, д. 8, кв. 14",
    addressExtra: "Подъезд 2, домофон 14К, 3 этаж",
    reportProblem: "Сообщить о проблеме",
  },
  login: {
    title: "Введите код",
    sentToPrefix: "Мы отправили 6-значный код на",
    email: "name@mail.ru",
    digitLabel: "Цифра",
    submit: "Войти",
    resendIn: "Отправить код ещё раз через",
    resend: "Отправить код повторно",
    trustTitle: "Быстрая авторизация",
    trustText: "Без паролей — просто одноразовый код",
    brandBadge: "Вжик",
  },
  profile: {
    title: "Профиль",
    name: "Александр П.",
    phone: "+7 900 000-00-00",
    email: "name@mail.ru",
    homeLabel: "Дом",
    home: "ул. Роз, 12",
    settings: "Настройки",
    items: [
      { id: "orders", label: "Мои заказы" },
      { id: "address", label: "Адрес доставки" },
      { id: "about", label: "О проекте" },
      { id: "contacts", label: "Контакты" },
    ],
    logout: "Выйти",
  },
  about: {
    title: "О проекте",
    lead: "«Вжик» — это коллективные закупки продуктов напрямую у производителей.",
    blocks: [
      {
        heading: "Фиксированная цена",
        text: "Покупатель получает оптовую цену производителя. Она не зависит от числа соседей.",
      },
      {
        heading: "Волна соседей",
        text: "Доставка дешевеет, когда заказ собирают вместе. Один курьер привозит продукты сразу нескольким соседям.",
      },
      {
        heading: "Из дома",
        text: "Все начинается с вашего дома: продукты привозят тем, кто живет рядом.",
      },
    ],
    back: "Назад",
  },
  contacts: {
    title: "Контакты",
    supportTitle: "Служба поддержки",
    supportText: "Отвечаем на вопросы с 8:00 до 22:00",
    methods: [
      { id: "chat", label: "Чат в приложении", value: "Онлайн" },
      { id: "phone", label: "Телефон", value: "8 800 000-00-00" },
      { id: "email", label: "Почта", value: "help@vzhik.ru" },
    ],
    back: "Назад",
  },
  kit: {
    link: "/ui-kit",
    buttons: "Кнопки",
    card: "Карточка",
    tabs: "Вкладки",
    progress: "Прогресс",
    field: "Поле",
    categories: "Категории",
    product: "Товар",
    menu: "Меню",
    sheet: "Нижняя панель",
  },
} as const;
